#!/bin/bash
#
#  _____ _______ _                         
# |_   _|__   __| |                        
#   | |    | |  | |__   ___ _ __ ___   ___ 
#   | |    | |  | '_ \ / _ \ '_ ` _ \ / _ \
#  _| |_   | |  | | | |  __/ | | | | |  __/
# |_____|  |_|  |_| |_|\___|_| |_| |_|\___|
#                                          
#ITheme I3 Config                                        
#Made by Amelia Yukii (https://transfem.social/@Amelia)
#https://github.com/Insert5StarName
#
gaps inner 10
gaps outer 3

set $mod Mod4
font CaskaydiaCove Nerd Font Mono:Regular 8
default_border pixel 1
exec --no-startup-id $HOME/.config/i3/layout.py 
exec --no-startup-id nm-applet
exec --no-startup-id dunst
exec --no-startup-id picom
exec --no-startup-id polybar
exec --no-startup-id nitrogen --restore
exec --no-startup-id blueman-tray
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle 
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle 
floating_modifier $mod
bindsym $mod+Return exec  kitty
bindsym $mod+Shift+c kill
bindsym $mod+d exec --no-startup-id rofi -show drun
bindsym $mod+a exec --no-startup-id thunar
bindsym $mod+Shift+d exec --no-startup-id pavucontrol

bindsym $mod+x exec --no-startup-id "scrot -a $(slop -f  '%x,%y,%w,%h') '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f'"

# Float Thunar if uncommented
#for_window [class="Thunar"] floating enable

bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+h split h

bindsym $mod+v split v

bindsym $mod+f fullscreen toggle
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle

set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

bindsym $mod+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+q exec "i3-msg exit"

mode "resize" {
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"
client.focused #732525 #0a0909 #f2b7b6 #732525 #732525
